version: '2'

services:
  base:
    image: node:18
    working_dir: &dir /usr/src/app 
    volumes:
    - type: bind
      source: .
      target: *dir
      consistency: cached
    - sublet_backend_node_modules:/usr/src/app/node_modules 
  
  install:
    extends:
      service: base
    command: npm install
  
volumes:
  sublet_backend_node_modules:
    external: true